---
variables:
  TEST_IMAGE: registry.gitlab.com/tarantool/enterprise/ansible-cartridge
  BUNDLE_VERSION: 1.10.3-93-g580699f
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - prebuild
  - test

docker-build-base:
  image: null
  stage: prebuild
  tags:
    - shell
  only:
    changes:
      - Dockerfile.test
      - .gitlab-ci.yml
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker pull ${TEST_IMAGE} || true
    - >
      docker build
      -t ${TEST_IMAGE}
      -f Dockerfile.test
      .
    - docker push ${TEST_IMAGE}
  after_script:
    - docker logout registry.gitlab.com

default:
  image: ${TEST_IMAGE}
  services:
    - name: docker:dind
      alias: localhost

  before_script:
    - docker info
    - python3 --version
    - ansible --version

test-enterprise:
  stage: test
  tags:
    - molecule-dind
  script:
    - ./linter.sh

    - cd .. && (rm -rf tarantool-cartridge || true)
    - cp -R ansible-cartridge tarantool-cartridge && cd tarantool-cartridge

    - TARANTOOL_VERSION=enterprise ./create-packages.sh
    - molecule test

test-opensource-1.10:
  stage: test
  tags:
    - molecule-dind
  script:
    - ./linter.sh

    - cd .. && (rm -rf tarantool-cartridge || true)
    - cp -R ansible-cartridge tarantool-cartridge && cd tarantool-cartridge

    - TARANTOOL_VERSION=opensource-1.10 ./create-packages.sh
    - molecule test

test-opensource-2.2:
  stage: test
  tags:
    - molecule-dind
  script:
    - ./linter.sh

    - cd .. && (rm -rf tarantool-cartridge || true)
    - cp -R ansible-cartridge tarantool-cartridge && cd tarantool-cartridge

    - TARANTOOL_VERSION=opensource-2.2 ./create-packages.sh
    - molecule test
